import { Inter, Orbitron, Fondamento, Merienda } from "next/font/google";
import "./globals.css";
import Navbar from "./components/shared/Navbar";

const inter = Inter({ subsets: ["latin"] });
const orbitron = Orbitron({ subsets: ["latin"] });
// const fondamento = Fondamento({ subsets: ["latin"], weight: "200" });
const merienda = Merienda({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={merienda.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
